id: default-oracle-application-page

info:
  name: Oracle Application Server Containers
  author: dhiyaneshDk
  severity: info
  metadata:
    shodan-query: http.title:"Oracle Application Server Containers"
  tags: tech,oracle

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - "<TITLE>Oracle Application Server Containers for J2EE 10g</TITLE>"
        part: body
