id: prometheus-exporter-detect
info:
  name: Prometheus exporter detect
  author: jarijaas
  severity: info
  description: Prometheus exporter detector
  tags: panel
  reference: https://github.com/prometheus/prometheus/wiki/Default-port-allocations

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - Exporter # Exporters have "Exporter" in the page title (e.g, Node Exporter, Bind Exporter and so on)
          - /metrics
        condition: and

    extractors: # Extract exporter name
      - type: regex
        part: body
        name: exporter_name
        group: 1
        regex:
          - "<title>(.*?)</title>"