id: sonic-wall-application

info:
  name: Sonic Wall Appliance Management Console
  author: DhiyaneshDk,Tess
  severity: info
  metadata:
    verified: true
    shodan-query: title:"Appliance Management Console Login"
  tags: panel,sonicwall,login

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login.do"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Appliance Management Console Login</title>'

      - type: status
        status:
          - 200
