id: cakephp-config

info:
  name: Cakephp Configuration File Disclosure
  author: DhiyaneshDk
  severity: medium
  reference:
    - https://book.cakephp.org/phinx/0/en/configuration.html
  metadata:
    verified: true
    shodan-query: html:"phinx.yml"
  tags: files,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phinx.yml"
      - "{{BaseURL}}/phinx.yaml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "host:"
          - "name:"
          - "pass:"
        condition: and

      - type: status
        status:
          - 200
