id: cloud-config

info:
  name: Cloud Config Yaml - File Disclosure
  author: DhiyaneshDK
  severity: medium
  reference: https://www.exploit-db.com/ghdb/7959
  metadata:
    verified: true
    shodan-query: html:"cloud-config.yml"
  tags: exposure,cloud,devops

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cloud-config.yml"
      - "{{BaseURL}}/core-cloud-config.yml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'ssh_authorized_keys'
          - '#cloud-config'
        condition: and

      - type: status
        status:
          - 200
