id: kubernetes-kustomization-disclosure

info:
  name: Kubernetes Kustomization Disclosure
  author: dhiyaneshDk
  severity: medium
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/kubernetes-kustomization-disclosure.json
  tags: exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/kustomization.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - "apiVersion:"
          - "resources:"
          - "namespace:"
          - "commonLabels:"
          - "Kustomization"

      - type: word
        part: body
        condition: or
        words:
          - "yaml"
          - "yml"

      - type: status
        status:
          - 200
