id: redmine-db-config
info:
  name: Detect Redmine Database Configuration
  author: geeknik
  description: Redmine is a flexible project management web application written using Ruby on Rails framework - https://redmine.org/projects/redmine
  severity: medium

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - adapter
          - database
          - host
        condition: and

      - type: status
        status:
          - 200