id: wgetrc-config

info:
  name: Wgetrc Configuration File Exposure
  author: DhiyaneshDK
  severity: medium
  metadata:
    verified: true
    shodan-query: html:".wgetrc"
  tags: devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wgetrc"
      - "{{BaseURL}}/.wgetrc"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '/etc/wgetrc'
          - 'wget.info'

      - type: word
        part: header
        words:
          - 'application/octet-stream'

      - type: status
        status:
          - 200
