id: esphome-panel

info:
  name: ESPHome Panel Detect
  author: fabaff
  severity: info
  metadata:
    verified: true
    shodan-query: title:"Login - ESPHome"
  tags: panel,esphome,iot

requests:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'class="esphome-header'

      - type: status
        status:
          - 200
