id: extreme-netconfig-ui

info:
  name: Extreme NetConfig UI Panel - Detect
  author: pussycat0x
  severity: info
  description: Extreme NetConfig UI panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    shodan-dork: 'http.title:"Extreme NetConfig UI"'
  tags: panel,tech,hiveos,extreme

requests:
  - method: GET
    path:
      - "{{BaseURL}}/index.php5"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>Extreme NetConfig UI</title>'
        condition: and

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - 'version" align="right" valign="bottom">([0-9.a-z]+)<\/td>'

# Enhanced by md on 2022/11/14
