id: netlify-cms

info:
  name: Netlify CMS Admin Login Panel - Detect
  author: sullo
  severity: info
  description: Netlify CMS admin login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: panel,netlify

requests:
  - method: GET
    path:
      - "{{BaseURL}}/admin/index.html"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Netlify CMS"
        part: body

# Enhanced by md on 2022/11/29
