id: golangci-config

info:
  name: GolangCI-Lint Configuration File Exposure
  author: Hardik-Solanki
  severity: low
  reference:
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
    - https://golangci-lint.run/usage/configuration/
  metadata:
    verified: true
    github-query: filename:golangci.yml
  tags: exposure,golang,devops,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.golangci.yml"
      - "{{BaseURL}}/.golangci.yaml"
      - "{{BaseURL}}/.golangci.toml"
      - "{{BaseURL}}/.golangci.json"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'linters:'
          - 'linters-settings:'
        condition: and

      - type: status
        status:
          - 200
