id: typo3-composer

info:
  name: Typo3 composer.json Exposure
  author: 0x_Akoko
  severity: low
  description: |
     The web application is based on Typo3 CMS. A sensitive file has been found. Access to such files must be restricted, as it may lead to disclosure of sensitive information about the web application.
  reference:
    - https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.0/Breaking-83302-ComposerRestrictsInstallationOfTypo3cms.html
  metadata:
    verified: true
    shodan-query: "X-TYPO3-Parsetime: 0ms"
  tags: typo3,cms,exposure,misconfig

requests:
  - method: GET
    path:
      - '{{BaseURL}}/typo3/sysext/install/composer.json'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "The Install Tool mounted as the module Tools>Install in TYPO3."
          - "typo3-cms-framework"
        condition: and

      - type: status
        status:
          - 200
