id: xampp-environment-variables

info:
  name: XAMPP Environment Variables Exposure
  author: melbadry9,DhiyaneshDK
  severity: low
  tags: exposure,xampp,files

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/printenv.pl"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<TITLE>Environment Variables</TITLE>"
          - "Environment Variables:"
        condition: and

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
