id: coremail-config-disclosure

info:
  name: Coremail - Config Discovery
  author: princechaddha
  severity: high
  description: Coremail configuration information was discovered.
  reference:
    - https://www.secpulse.com/archives/107611.html
  tags: config,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}/mailsms/s?func=ADMIN:appState&dumpConfig=/'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<object name=\"cm_md_db\">"
          - 'containerDefinitions'
          - '<string name="User">coremail</string>'
          - '<string name="EnableCoremailSmtp">'
        condition: or

      - type: status
        status:
          - 200

# Enhanced by mp on 2022/07/15
