id: msmtp-config

info:
  name: Msmtp Config Exposure
  author: geeknik
  severity: high
  description: msmtp is a very simple and easy to use SMTP client with fairly complete sendmail compatibility.
  reference:
    - https://wiki.archlinux.org/title/Msmtp
  metadata:
    verified: true
  tags: exposure,generic,msmtp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.msmtprc"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'account'
          - 'host'
          - 'from'
          - 'auth'
          - 'tls'
        condition: and

      - type: word
        part: header
        words:
          - 'text/plain'
          - 'octet-stream'
        condition: or

      - type: status
        status:
          - 200
