id: netlify-takeover

info:
  name: netlify takeover detection
  author: 0xPrial,pdteam
  severity: high
  reference:
    - https://github.com/EdOverflow/can-i-take-over-xyz/issues/40
    - https://monish-basaniwal.medium.com/how-i-found-my-first-subdomain-takeover-vulnerability-b7d5c17b61fd
    - https://github.com/EdOverflow/can-i-take-over-xyz/pull/289
  tags: takeover,netlify

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - Host != ip

      - type: word
        part: body
        words:
          - "Not Found - Request ID:"
        case-insensitive: true

      - type: word
        part: header
        words:
          - "Netlify"
