id: owncloud-config

info:
  name: owncloud config Disclosure
  author: Mahendra Purbia (Mah3Sec_)
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/owncloud/config/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Index of'
          - 'owncloud/config'
        condition: and
        part: body

      - type: status
        status:
          - 200