id: rackup-config-ru

info:
  name: Rackup config.ru Configuration Exposure
  author: DhiyaneshDk
  severity: info
  reference:
    - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
    - https://learn.co/lessons/config-ru-tutorial
  metadata:
    verified: true
    shodan-query: html:"config.ru"
  tags: exposure,files,config,rackup

requests:
  - method: GET
    path:
      - '{{BaseURL}}/config.ru'

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "run Rails.application"
          - "/config/environment"
        condition: and

      - type: word
        part: body
        words:
          - "Bundler.require"
          - "require 'rubygems'"
        condition: and
