id: rollup-js-config

info:
  name: Rollup.js Configuration Exposure
  author: DhiyaneshDK
  severity: info
  reference:
    - https://rollup.docschina.org/guide/en/#configuration-files
  metadata:
    verified: true
    shodan-query: html:"rollup.config.js"
  tags: exposure,devops,cicd,rollupjs

requests:
  - method: GET
    path:
      - '{{BaseURL}}/rollup.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'export default ['
          - 'input:'
        condition: and

      - type: status
        status:
          - 200
