id: s3cfg-config

info:
  name: S3CFG Configuration - File Exposure
  author: geeknik,DhiyaneshDK
  severity: unknown
  reference:
    - https://s3tools.org/kb/item14.htm
  tags: amazon,s3,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.s3cfg"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "access_key"
          - "bucket_location"
          - "secret_key"
        condition: and

      - type: word
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200
