id: scrutinizer-config

info:
  name: Scrutinizer Config File Exposure
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    shodan-query: html:"scrutinizer.yml"
  reference:
    - https://scrutinizer-ci.com/docs/configuration
  tags: exposure,scrutinizer,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}/.scrutinizer.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'build:'
          - 'filter:'
          - 'tools:'
        condition: and

      - type: status
        status:
          - 200
