id: amazon-docker-config

info:
  name: Dockerrun AWS Configuration Page - Detect
  author: pdteam
  severity: medium
  description: Dockerrun AWS configuration page was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags: config,exposure,aws,devops

requests:
  - method: GET
    path:
      - '{{BaseURL}}/Dockerrun.aws.json'
    matchers:
      - type: word
        words:
          - 'AWSEBDockerrunVersion'
          - 'containerDefinitions'
        condition: and

# Enhanced by md on 2023/02/08
