id: cakephp-config

info:
  name: CakePHP Configuration File - Detect
  author: DhiyaneshDk
  severity: medium
  description: CakePHP configuration file was detected.
  reference:
    - https://book.cakephp.org/phinx/0/en/configuration.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"phinx.yml"
  tags: files,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phinx.yml"
      - "{{BaseURL}}/phinx.yaml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "host:"
          - "name:"
          - "pass:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/08
