id: circleci-ssh-config

info:
  name: CircleCI SSH Configuration - Detect
  author: geeknik
  severity: medium
  description: CircleCI ssh-config file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags: config,exposure,circleci

requests:
  - method: GET
    host-redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/.circleci/ssh-config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Host"
          - "HostName"
          - "IdentityFile"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
