id: circleci-config

info:
  name: CircleCI Configuration File - Detect
  author: geeknik
  severity: medium
  description: CircleCI config.yml file was detected.
  reference:
    - https://circleci.com/docs/2.0/sample-config/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags: config,exposure,circleci

requests:
  - method: GET
    host-redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/.circleci/config.yml"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'regex("^version: ", body) && contains(body, "jobs:")'

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
