id: awstats-config

info:
  name: AWStats Config - Detect
  author: sheikhrishad
  severity: info
  description: AWStats configuration information was detected.
  reference: https://www.awstats.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: config,exposure,awstats

requests:
  - method: GET
    path:
      - "{{BaseURL}}/awstats/"
      - "{{BaseURL}}/awstats.conf"

    matchers:
      - type: word
        words:
          - "AWSTATS CONFIGURE"
          - "MAIN SETUP SECTION"
        condition: and

      - type: word
        words:
          - "Index of /awstats"
          - "Parent Directory"
        condition: and

# Enhanced by mp on 2023/02/05
