id: babel-config-exposure

info:
  name: Babel Configuration Exposure
  author: DhiyaneshDK
  severity: info
  reference:
    - https://babeljs.io/docs/en/configuration
  metadata:
    verified: true
    shodan-query: html:"babel.config.js"
  tags: exposure,config,file

requests:
  - method: GET
    path:
      - '{{BaseURL}}/babel.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'module.exports = {'
          - 'presets: ['
        condition: and

      - type: status
        status:
          - 200
