id: cisco-network-config

info:
  name: Cisco System Network Configuration Page - Detect
  author: DhiyaneshDk
  severity: info
  description: Cisco System Network configuration page was detected. Page lists whole network configuration and internal logs of Cisco IP phones.
  reference:
    - https://www.exploit-db.com/ghdb/5430
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: exposure,cisco,edb,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/CGI/Java/Serviceability?adapter=device.statistics.configuration"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Network Configuration"
        part: body

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
