id: cypress-web-config

info:
  name: Cypress Oxygen Web Page Configuration
  author: tess
  severity: info
  metadata:
    verified: true
    shodan-query: http.title:"PendingInstallVZW - Web Page Configuration"
  tags: exposure,cypress,pendinginstallvzw,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'PendingInstallVZW - Web Page Configuration'
          - 'alt="Cypress Oxygen-3'
        condition: and

      - type: status
        status:
          - 200
