id: gcloud-config-default

info:
  name: Google Cloud Default Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Google Cloud default configuration was detected.
  reference: https://cloud.google.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"access_tokens.db"
  tags: google,cloud,devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/configurations/config_default"
      - "{{BaseURL}}/.config/gcloud/configurations/config_default"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[core]'
          - 'account'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
