id: gcloud-config-default

info:
  name: Google Cloud Config Default
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    shodan-query: html:"access_tokens.db"
  tags: google,cloud,devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/configurations/config_default"
      - "{{BaseURL}}/.config/gcloud/configurations/config_default"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[core]'
          - 'account'
        condition: and

      - type: status
        status:
          - 200
