id: guard-config

info:
  name: Guardfile Configuration Exposure
  author: DhiyaneshDK
  severity: info
  metadata:
    verified: true
    shodan-query: html:"Guardfile"
  reference:
    - https://github.com/guard/guard
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
  tags: exposure,file,guard,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}/Guardfile'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'guard :'
          - 'end'
        condition: and

      - type: status
        status:
          - 200
