id: httpd-config

info:
  name: Apache httpd Config File - Detect
  author: sheikhrishad
  severity: info
  description: Apache httpd configuration information was detected.
  reference: https://httpd.apache.org/docs/current/configuring.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags: config,exposure,httpd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/httpd.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "LoadModule"
          - "# LoadModule"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
