id: phpsec-config

info:
  name: phpspec Config - Detect
  author: DhiyaneshDK
  severity: info
  description: phpspec configuration information was detected.
  reference: https://phpspec.net/en/stable/cookbook/configuration.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"phpspec.yml"
  tags: exposure,phpsec,php,devops,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.phpspec.yml"
      - "{{BaseURL}}/phpspec.yml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'suites:'
          - 'main:'
          - 'namespace:'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
