id: procfile-config

info:
  name: Procfile Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Procfile configuration information was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"Procfile"
  tags: devops,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/Procfile"

    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - '^web:'

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
