id: rackup-config-ru

info:
  name: Rackup Configuration - Detect
  author: DhiyaneshDk
  severity: info
  description: Rackup configuration information was detected.
  reference:
    - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
    - https://learn.co/lessons/config-ru-tutorial
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"config.ru"
  tags: exposure,files,config,rackup

requests:
  - method: GET
    path:
      - '{{BaseURL}}/config.ru'

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "run Rails.application"
          - "/config/environment"
        condition: and

      - type: word
        part: body
        words:
          - "Bundler.require"
          - "require 'rubygems'"
        condition: and

# Enhanced by mp on 2023/02/05
