id: rubocop-config

info:
  name: Rubocop Configuration File Exposure
  author: DhiyaneshDk
  severity: info
  reference:
    - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
    - https://github.com/rubocop/rubocop
  metadata:
    verified: true
    shodan-query: html:"rubocop.yml"
  tags: exposure,files,config,ruby

requests:
  - method: GET
    path:
      - '{{BaseURL}}/.rubocop.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "AllCops:"
          - "Include:"
          - "Exclude:"
        condition: and

      - type: status
        status:
          - 200
