id: s3cmd-config

info:
  name: S3CMD Configuration - Detect
  author: Ice3man
  severity: info
  description: S3CMD configuration information was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: amazon,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/s3cmd.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[default]'
          - 'access_key'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
