id: samba-config

info:
  name: Samba Config - Detect
  author: sheikhrishad
  severity: info
  description: Samba configuration information was detected.
  reference: https://www.samba.org/samba/docs/using_samba/ch06.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: config,exposure,smb,samba

requests:
  - method: GET
    path:
      - "{{BaseURL}}/smb.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "configuration file"
          - "samba"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
