id: scrutinizer-config

info:
  name: Scrutinizer Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Scrutinizer configuration information was detected.
  reference:
    - https://scrutinizer-ci.com/docs/configuration
    - https://scrutinizer-ci.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"scrutinizer.yml"
  tags: exposure,scrutinizer,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}/.scrutinizer.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'build:'
          - 'filter:'
          - 'tools:'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2023/02/05
