id: stestr-config

info:
  name: Stestr Configuration File Exposure
  author: Hardik-Solanki
  severity: info
  reference:
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
    - https://stestr.readthedocs.io/en/latest/MANUAL.html
  metadata:
    verified: true
    github-query: filename:stestr.conf
  tags: exposure,stestr,config,files

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.stestr.conf"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[DEFAULT]'
          - 'test_path='
        condition: and

      - type: status
        status:
          - 200
